/* data based on PAUL CHAPMAN's blog and github https://spring.io/blog/2015/07/14/microservices-with-spring */
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('a@a.com', 'Rachel Corrie', 'desc.2');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('b@b.com', 'Dollie R. Schnidt', 'desc.1');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('c@c.com', 'Cornelia J. LeClerc', 'desc.3');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('d@d.com', 'Cynthia Rau', 'desc.4');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('e@e.com', 'Douglas R. Cobbs', 'desc.5');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('f@f.com', 'Michael Patel', 'desc.6');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('g@g.com', 'Suzanne Wong', 'desc.7');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('h@h.com', 'Ivan C. Jaya', 'desc.8');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('i@i.com', 'Ida Ketterer', 'desc.9');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('j@j.com', 'Laina Ochoa Lucero', 'desc.10');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('k@k.com', 'Wesley M. Montana', 'desc.11');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('l@l.com', 'Leslie F. McCleary', 'desc.12');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('m@m.com', 'Sayeed D. Mudra', 'desc.13');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('n@n.com', 'Pietronella J. Domingo', 'desc.14');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('o@o.com', 'John S. O''Leary', 'desc.15');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('p@p.com', 'Gladys D. Smith', 'desc.16');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('q@q.com', 'Sally O. Thygesen', 'desc.17');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('r@r.com', 'Rachel Vogt', 'desc.18');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('s@s.com', 'Julia DeLong', 'desc.19');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('t@t.com', 'Mark T. Rizzoli', 'desc.20');
insert into T_USER (EMAIL, NAME, DESCRIPTION) values ('u@u.com', 'Maria J. Angelo', 'desc.21');
